/*
 * This source file was generated by the Gradle 'init' task
 */
package desktop;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testExample() {
        assertTrue("This test should pass", true);
    }
}
